apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteoproxy-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meteoproxy-java
  template:
    metadata:
      labels:
        app: meteoproxy-java
    spec:
      containers:
        - name: meteoproxy-java
          image: aranve/meteoproxy-java:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          resources:
            requests:
              memory: 256Mi
              cpu: 0.05
            limits:
              memory: 512Mi
              cpu: 0.25

